trigger:
- master

pool:
  name: MyAGPool_VM-SQLSVR-TMG-F
  demands: msbuild

steps:
- task: MSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: 'SSRS_REPORT'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'SSRS_REPORT'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    filePath: '$(build.artifactstagingdirectory)/DeploySSRSReportsTesting.ps1'
    arguments: '$(DataSourceFolder) $(DataSourceFile) $(ReportServerUri) $(DBServerName) $(DatabaseName) $(TargetFolder) $(DataSourceUserName) $(DataSourcePassword)'


