trigger:
- testing

pool:
  name: MyAGPool_VM-SQLSVR-TMG-F
  demands: msbuild


variables:
- group: DEV-VG


stages:
- stage: BUILD
  jobs:
  - job: Build
    steps:
      - task: MSBuild@1
        displayName: 'Build solution'
        inputs:
          solution: 'SSRS_REPORT'

- stage: COPY
  jobs:  
  - job: Copy
    steps:


    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(agent.builddirectory)'
        Contents: '**\*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

- stage: PUBLISH
  jobs:  
  - job: Publish
    steps:
    - task: CopyPublishBuildArtifacts@1
      inputs:
        Contents: '**\*'
        ArtifactName: 'MyArtifactBuildSSRSY'
        ArtifactType: 'Container'
        
- stage: DEPLOY
  jobs:  
  - job: Deploy-Dev
    steps:
    - task: PowerShell@2
      displayName: 'PowerShell Script for DEV Env.'
      inputs:
          filePath: '$(build.artifactstagingdirectory)/MyArtifactBuildSSRSY/SSRS_REPORT/DeploySSRSReportsTesting.ps1'
          arguments: '$(DataSourceFolder1) $(build.artifactstagingdirectory)/MyArtifactBuildSSRSY/SSRS_REPORT/$(DataSourceFile1) $(ReportServerUri) $(DBServerName) $(DatabaseName) $(TargetFolder1) $(DataSourceUserName) $(DSPassword)'

- stage: DEPLOY
  jobs:  
  - job: Deploy-PRD
    steps:
    - task: PowerShell@2
      displayName: 'PowerShell Scrip for PRD Env.'
      inputs:
          filePath: '$(build.artifactstagingdirectory)/MyArtifactBuildSSRSY/SSRS_REPORT/DeploySSRSReportsTesting.ps1'
          arguments: '$(DataSourceFolder1) $(build.artifactstagingdirectory)/MyArtifactBuildSSRSY/SSRS_REPORT/$(DataSourceFile1) $(ReportServerUri) $(DBServerName) $(DatabaseName) $(TargetFolder1) $(DataSourceUserName) $(DSPassword)'
