trigger:
- testing

pool:
  name: MyAGPool_VM-SQLSVR-TMG-F
  demands: msbuild


variables:
- group: DEV-VG


stages:
- stage: BUILD
  jobs:
  - job: Build
    steps:

      - task: MSBuild@1
        displayName: 'Build solution'
        inputs:
          solution: 'SSRS_REPORT'

- stage: DEPLOY
  jobs:  
  - job: Deploy
    steps:


    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(agent.builddirectory)'
        Contents: '**\*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        

    - task: PowerShell@2
      displayName: 'PowerShell Script for DEV Env.'
      inputs:
          filePath: '$(build.artifactstagingdirectory)/DeploySSRSReportsTesting.ps1'
          arguments: '$(DataSourceFolder1) $(build.artifactstagingdirectory)/$(DataSourceFile1) $(ReportServerUri) $(DBServerName) $(DatabaseName) $(TargetFolder1) $(DataSourceUserName) $(DSPassword)'

    - task: PowerShell@2
      displayName: 'PowerShell Scrip for PRD Env.'
      inputs:
          filePath: '$(build.artifactstagingdirectory)/DeploySSRSReportsTesting.ps1'
          arguments: '$(DataSourceFolder1) $(build.artifactstagingdirectory)/$(DataSourceFile1) $(ReportServerUri) $(DBServerName) $(DatabaseName) $(TargetFolder1) $(DataSourceUserName) $(DSPassword)'

