trigger:
- master

pool:
  name: MyAGPool_VM-SQLSVR-TMG-F
  demands: msbuild

variables:
- group: DEV-VG-YAML
- group: PRD-VG-YAML
- name: my-passed-variable
  value: $[variables.DataSourceFolder] $[variables.DataSourceFile]

stages:
- stage: BUILD
  jobs:
  - job: Build
    steps:
      - script: echo $(DEV-VG-YAML) # uses macro syntax
      - script: echo $(my-passed-variable)

      - task: MSBuild@1
        displayName: 'Build solution'
        inputs:
          solution: 'SSRS_REPORT'
- stage: DEPLOY
  jobs:  
  - job: Deploy
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'SSRS_REPORT'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        filePath: '$(build.artifactstagingdirectory)/DeploySSRSReportsTesting.ps1'
        arguments: '$(DataSourceFolder) $(build.artifactstagingdirectory)/$(DataSourceFile) $(ReportServerUri) $(DBServerName) $(DatabaseName) $(TargetFolder) $(DataSourceUserName) $(DataSourcePassword)'


