trigger:
- TESTING-2

pool:
  name: MyAGPool_VM-SQLSVR-TMG-F
  demands: msbuild

stages:
- stage: BUILD
  jobs:
  - job: Build
    steps:
      - task: MSBuild@1
        displayName: 'Build solution'
        inputs:
          solution: 'SSRS_REPORT'

- stage: COPY
  jobs:  
  - job: Copy
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(agent.builddirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'


- stage: DEPLOY_DEV
  variables:
  - group: DEV-VG-TESTING2
  jobs:  
  - job: Deploy_Dev
    steps:
    - task: CopyPublishBuildArtifacts@1
      inputs:
        Contents: '**\*'
        ArtifactName: 'MyArtifactBuildSSRSY-TESTING2'
        ArtifactType: 'Container'
    - task: PowerShell@2
      displayName: 'PowerShell Script for DEV Env.'
      inputs:
          filePath: '$(build.artifactstagingdirectory)/MyArtifactBuildSSRSY-TESTING2/SSRS_REPORT/DeploySSRSReportsTesting.ps1'
          arguments: '$(DataSourceFolder1) $(build.artifactstagingdirectory)/MyArtifactBuildSSRSY-TESTING2/SSRS_REPORT/$(DataSourceFile1) $(ReportServerUri) $(DBServerName) $(DatabaseName) $(TargetFolder1) $(DataSourceUserName) $(DSPassword)'


- stage: DEPLOY_PRD
  variables:
  - group: PRD-VG-TESTING2
  jobs:  
  - job: Deploy_Prd
    steps:
    - task: CopyPublishBuildArtifacts@1
      inputs:
        Contents: '**\*'
        ArtifactName: 'MyArtifactBuildSSRSY'
        ArtifactType: 'Container'
    - task: PowerShell@2
      displayName: 'PowerShell Scrip for PRD Env.'
      inputs:
          filePath: '$(build.artifactstagingdirectory)/MyArtifactBuildSSRSY-TESTING2/SSRS_REPORT/DeploySSRSReportsTesting.ps1'
          arguments: '$(DataSourceFolder1) $(build.artifactstagingdirectory)/MyArtifactBuildSSRSY-TESTING2/SSRS_REPORT/$(DataSourceFile1) $(ReportServerUri) $(DBServerName) $(DatabaseName) $(TargetFolder1) $(DataSourceUserName) $(DSPassword)'
